# -*- coding: utf-8 -*-
"""HW3_KatiJohnson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_ZORzN0-4l-m6Y-Vy1E9oreBcCJKOx6

Please see examples we did in class. Questions are just variations of what we did earlier.

**Q1**. Please read WorldCupMatches.csv to a data frame to proceed
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

wcdata = pd.read_csv('/content/drive/MyDrive/CSC302/DATA/WorldCupMatches.csv')
wcdata.head()

"""**Q2** Using seaborn's displot draw density curves to show the distributions of Home Team Goals for every year. """

sns.displot(wcdata, x="Home Team Goals", hue="Year", kind="kde")

"""**Q3** Draw violin plots to summarize Home Team Goals distributions for each year by using seaborn. Notice that labels are really cluttered. Then please refer to the earlier notebooks to have labels to appear on only select years which end with 0. You can use ax handle to call ax.set_xticklables(labels) for the labels your prepared."""

fig, ax = plt.subplots(figsize=(10, 5))
sns.violinplot(data=wcdata, x='Year', y='Home Team Goals')
labels=[y if y%10==0 else None for y in list(wcdata.Year.unique())]
loc = range(len(labels))
plt.xticks(loc, labels, rotation='vertical')

"""**Q4** Please install joypy. Then visualize distributions for Home Team Goals and Away Team Goals' for each year. Once you visualize, please add  plt.style.use('seaborn-white') to see how colors change in your second run. Please also add the legend which you can find from the function prototype.


"""

!pip install joypy

import joypy as jp

plt.style.use('seaborn-white')
jp.joyplot(wcdata, by="Year", column=['Home Team Goals', 'Away Team Goals'],  range_style='own', 
                          grid="y", linewidth=1, legend=True, figsize=(6,5),
                          title="Goals by Year")

"""**Q5** Please use groupby function on Home Team Initials to see the sum of Home Team Goals which can be saved to another data frame by adding .reset_index() end the end of your line. 

Then use your new data frame to visualize those total Home Team Goals for your top 5 countries with a bar plot (You can use Home Team Initials). You can use use df.sort_values() function on your data frame by tweaking the ascending option.

Notice that your x-axis will be having country initials, and y-axis will show the total number of Home Team Goals. 


"""

df = wcdata.groupby(["Home Team Initials"])["Home Team Goals"].sum().reset_index(0)
df = df.sort_values(by=['Home Team Goals'], ascending=False)
top5 = df.head(5)


plt.figure(figsize=(15, 3))
fig, ax = plt.subplots()

ax =  plt.bar(top5['Home Team Initials'],top5['Home Team Goals']) #you can call a plot function by passing the data as your parameters
ax = plt.gca() #get current axis
fig = plt.gcf()
ax.set_ylabel("Total Home Team Goals")
ax.set_xlabel("Home Team Initials")

"""**Q6** Please extract the rows for your top 4 countries (Home Team Initials') with the help of the previous question's answer. Then use joyplot again to visualize densities for 'Home Team Goals' and	'Away Team Goals' on the horizantal axis. Notice that your y-axis labels will be your country initials (Home Team Initials'). Make sure that your legend is visible and use 'dark_background' by calling plt.style.use again.


"""

df2 = wcdata.loc[(wcdata['Home Team Initials'] == 'BRA') | (wcdata['Home Team Initials'] == 'ARG')|(wcdata['Home Team Initials'] == 'FRG')|(wcdata['Home Team Initials'] == 'ITA')|(wcdata['Home Team Initials'] == 'HUN')]

plt.style.use('dark_background')
jp.joyplot(df2, by="Home Team Initials", column=['Home Team Goals', 'Away Team Goals'],  range_style='own', 
                          grid="y", linewidth=1, legend=True, figsize=(6,5),
                          title="Goals by Year")

"""**Q7** Please install seaborn_qqplot as shown below. Then draw a qqplot to compare probability distributions of Home Team Goals and Away Team Goals. Please comment on your finding. Do you think their distributions agree with each other? Please justify your answer by explaining the figure you obtained."""

!pip install seaborn_qqplot

from seaborn_qqplot import pplot #seaborn-qqplot is a seaborn extension adding qqplots.
plt.style.use('ggplot') #this is to change the color theme. 

pplot(data=wcdata, x="Home Team Goals", y="Away Team Goals", kind='qq', display_kws={"identity":True}, height=4, aspect=2)

#Finding shows that the distributions don't agree exactly which makes sense because the more home team goals scored, the fewer away team goals typically would be scored (given the home team is so strong)